export const types = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
  SET_PRODUCTS: "SET_PRODUCTS",
  TOGGLE_CREATE: "TOGGLE_CREATE",
  CREATE_PRODUCT: "CREATE_PRODUCT",
};
